---
- name: Selenoid | Run CM container, download browser images and run selenoid
  docker_container:
    name: cm
    image: 'aerokube/cm:{{ selenoid_cm_version }}'
    state: started
    pull: true
    recreate: true
    restart: true
    restart_policy: unless-stopped
    timeout: 600
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '{{ selenoid_config_dir }}:/root'
      - '{{ selenoid_config_dir }}/video:/opt/selenoid/video/'
      - '{{ selenoid_config_dir }}/logs:/opt/selenoid/logs/'
    env:
      OVERRIDE_HOME: '{{ selenoid_config_dir }}'
      OVERRIDE_VIDEO_OUTPUT_DIR: '{{ selenoid_config_dir }}/video'
    command: >
      selenoid start
        --last-versions 3
        --args '-limit 15'
        --vnc
        --tmpfs 512
        --force
